chipy_voter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib.flatpages import views
from django.contrib import admin

urlpatterns = [
    url(r'^login/$', 'chipy_voter.apps.users.views.login', name="login"),
    url(r'^logout/$', 'chipy_voter.apps.users.views.logout',),
    url(r'^admin/', include(admin.site.urls)),
    url('topics/', include('vote_tool.urls', namespace='topics')),
    url('social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^$', views.flatpage, {"url": "/index/"}, name="index"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote_tool/urls.py
from django.conf.urls import url
from .views import (
    VoteTopicListView,
    VoteView, VoteChoiceSubmissionView, VoteChoiceSubmissionSuccessView)

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$',
        VoteTopicListView.as_view(),
        {"view": "list"},
        name="topic_view"),
    url(r'^(?P<slug>[\w-]+)/submit/$',
        VoteChoiceSubmissionView.as_view(),
        name="topic_submit"),
    url(r'^(?P<slug>[\w-]+)/submit/success/$',
        VoteChoiceSubmissionSuccessView.as_view(),
        name="topic_submit_success"),
    url(r'^(?P<slug>[\w-]+)/choice/(?P<choice_id>[\d]+)/$',
        VoteView.as_view(),
        name="topic_vote_view"),
]

vote_tool/models.py
from __future__ import unicode_literals
import datetime
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from . import managers
from . import fields


class MetaMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class VotingTopic(MetaMixin, models.Model):

    VIEW_PAGE_CHOICES = ((1, "Allow List View"), (2, "Allow Card View"))

    title = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)
    submission_information = models.TextField(
        blank=True, null=True,
        help_text="Information to provide to Choice submitters.")

    list_page_view = fields.MultiSelectField(
        default=[x[0] for x in VIEW_PAGE_CHOICES],
        max_length=250, blank=True, choices=VIEW_PAGE_CHOICES)
    list_page_voting = models.BooleanField(
        "Allow voting on the list page.",
        default=False)
    anonymous_voting = models.BooleanField(
        "Allow anonymous voting",
        default=False)
    voting_enabled_date = models.DateTimeField(
        default=datetime.datetime.now, blank=True)
    require_approval = models.BooleanField(
        "Vote Choice Submission Requires Approval", default=True)

    vote_headers = fields.VoteHeaderField(blank=True, null=True)

    objects = managers.VotingTopicQuerySet.as_manager()

    def __str__(self):
        return "{title}".format(title=self.title)

    class Meta:
        verbose_name = "Voting Topic"
        verbose_name_plural = "Voting Topics"

    def get_absolute_url(self):
        return reverse('topics:topic_view', args=[str(self.slug)])

    def choices(self):
        kwargs = {}
        if self.require_approval:
            kwargs['approved'] = True
        return self.votechoice_set.filter(**kwargs)

    def votes(self):
        return Vote.objects.filter(choice__topic=self)

    def enable_list_view(self):
        return True if u'1' in self.list_page_view else False

    def enable_card_view(self):
        return True if u'2' in self.list_page_view else False


@python_2_unicode_compatible
class VoteChoice(MetaMixin, models.Model):
    topic = models.ForeignKey(VotingTopic)
    approved = models.BooleanField("Approved?", default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    text = models.CharField(max_length=255)

    picture = models.ImageField(blank=True, null=True, upload_to="votechoices")
    description = models.TextField(blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    link_text = models.CharField(max_length=64, blank=True, null=True)

    def get_link_text(self):
        return self.link_text if self.link_text else self.link

    def __str__(self):
        return "{topic}: {text}".format(topic=self.topic, text=self.text)

    class Meta:
        verbose_name = "Voting Choice"
        verbose_name_plural = "Voting Choices"


@python_2_unicode_compatible
class Vote(MetaMixin, models.Model):
    choice = models.ForeignKey(VoteChoice)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    vote = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "{choice}".format(choice=self.choice)

    class Meta:
        verbose_name = "Vote"
        verbose_name_plural = "Votes"

vote_tool/forms.py
from django import forms
from .models import Vote, VoteChoice


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = []

    def __init__(self, user, topic_slug, choice, *args, **kwargs):
        self.user = user
        self.topic_slug = topic_slug
        self.choice = choice
        super(VoteForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(VoteForm, self).clean()
        if Vote.objects.filter(choice__topic__slug=self.topic_slug, user=self.user):
            raise forms.ValidationError(
                "You may only vote once.")
        return cleaned_data


class VoteChoiceForm(forms.ModelForm):

    class Meta:
        model = VoteChoice
        fields = ['text', 'description', 'picture', 'link', 'link_text']

vote_tool/views.py
from django.contrib import messages
from django.views.generic import DetailView, FormView, CreateView, TemplateView
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import VotingTopic, VoteChoice
from .forms import VoteForm, VoteChoiceForm
from django.shortcuts import redirect, get_object_or_404


class VoteTopicListView(DetailView):
    model = VotingTopic
    template_name = "vote_tool/topic_list.html"
    http_method_names = [u'get']
    context_object_name = 'topic'

    def get_context_data(self, **kwargs):
        if self.request.GET.get('view') == "list":
            self.view = "list"
        else:
            self.view = "card"
        context = super(VoteTopicListView, self).get_context_data(**kwargs)
        context['view'] = self.view
        return context


class VoteChoiceSubmissionView(CreateView):
    http_method_names = [u'post', u'get']
    template_name = "vote_tool/vote_choice_submit.html"
    model = VoteChoice
    form_class = VoteChoiceForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.topic_slug = kwargs.get('slug')
        self.topic = get_object_or_404(
            VotingTopic,
            slug=self.topic_slug)
        return super(VoteChoiceSubmissionView, self).dispatch(
            request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.topic = self.topic
        self.object.save()
        return super(VoteChoiceSubmissionView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(VoteChoiceSubmissionView, self).get_context_data(
            **kwargs)
        context['topic'] = self.topic
        return context

    def get_success_url(self):
        url = reverse('topics:topic_submit_success', args=[self.topic_slug])
        return url


class VoteChoiceSubmissionSuccessView(TemplateView):
    template_name = "vote_tool/vote_choice_submit_success.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.topic_slug = kwargs.get('slug')
        self.topic = get_object_or_404(
            VotingTopic,
            slug=self.topic_slug)
        return super(VoteChoiceSubmissionSuccessView, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(VoteChoiceSubmissionSuccessView, self).get_context_data(
            **kwargs)
        context['topic'] = self.topic
        return context


class VoteView(FormView):
    http_method_names = [u'post']
    context_object_name = 'topic'
    form_class = VoteForm

    def get_success_url(self):
        url = reverse('topics:topic_view', args=[self.topic_slug])
        return url

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.topic_slug = kwargs.get('slug')
        self.choice_id = kwargs.get('choice_id')
        self.user = request.user
        self.choice = get_object_or_404(
            VoteChoice,
            id=self.choice_id,
            topic__slug=self.topic_slug)
        return super(VoteView, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(
            user=self.user, topic_slug=self.topic_slug,
            choice=self.choice, **self.get_form_kwargs())

    def form_invalid(self, form):
        messages.error(self.request, 'Unable to save vote. %s' % form.errors)
        return redirect(self.get_success_url())

    def form_valid(self, form):
        messages.info(self.request, 'Vote submitted.')
        vote = form.save(commit=False)
        vote.user = self.request.user
        vote.choice = self.choice
        vote.value = 1
        vote.save()
        return redirect(self.get_success_url())

vote_tool/templates/vote_tool/topic_list.html
{% extends "base.html" %}
{% load thumbnail staticfiles bleach_tags %}


{% block content %}
<h1>{{ topic.title }}</h1>
<p class="lead">{{ topic.description|bleach|safe }}</p>

  <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red" href="{% url 'topics:topic_submit' topic.slug %}">
      <i class="large material-icons">+</i>
    </a>
  </div>

{% if topic.enable_card_view %}
<a href="{% url 'topics:topic_view' topic.slug %}?view=card" class="btn btn-default" type="submit">
    <span class="typcn typcn-th-large-outline"><span></a>
{% endif %}
{% if topic.enable_list_view %}
<a href="{% url 'topics:topic_view' topic.slug %}?view=list" class="btn btn-default" type="submit">
    <span class="typcn typcn-th-list-outline"><span></a>
{% endif %}

{% if view == "list" %}
<div class="topic-list row">
  <ul class="collection">
  {% for choice in topic.choices %}
  <li class="collection-item avatar">

    {% if choice.picture %}
    {% thumbnail choice.picture "100x100" crop="center" as im %}
     <img src="{% static im.url %}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
    {% endif %}
    <a href="{{ choice.link }}" class="secondary-content"><i class="material-icons">{{ choice.get_link_text }}</i></a>

    <span class="title">{{ choice.text }}</span>
    <p>{{ choice.description }}</p>

    {% if topic.list_page_voting %}
    <form action="{% url 'topics:topic_vote_view' topic.slug choice.id %}" method="post">{% csrf_token %}
        <button class="btn waves-effect waves-light right-align" type="submit" name="action">Vote</button>
    </form>
    {% endif %}
  </li>
  {% empty %}
  <p>There are no approved choices yet.  <a href="{% url 'topics:topic_submit' topic.slug %}">Submit one!</a></p>
  {% endfor %}
  </ul>
</div>
{% endif %}


{% if view == "card" %}
<div class="row">
  {% for choice in topic.choices %}
  <div class="col s12 m6 grid-example">
    <div class="card large">
      <div class="card-image">

      {% if choice.picture %}
      {% thumbnail choice.picture "300x300" crop="center" as im %}
       <img class="" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
      {% endif %}

        <span class="card-title">{{ choice.text }}</span>
      </div>
      <div class="card-content">
        <p>{{ choice.description }}</p>
      </div>
      <div class="card-action">
        {% if topic.list_page_voting %}
        <form action="{% url 'topics:topic_vote_view' topic.slug choice.id %}" method="post">{% csrf_token %}
            <button class="btn waves-effect waves-light right-align" type="submit" name="action">Vote</button>
        </form>
        {% endif %}
        {% if choice.link %}
        Link: <a href="{{ choice.link }}">{{ choice.get_link_text }}</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% empty %}
  <p>There are no approved choices yet.  <a href="{% url 'topics:topic_submit' topic.slug %}">Submit one!</a></p>
  {% endfor %}
</div>
{% endif %}


{% endblock %}

vote_tool/templates/vote_tool/vote_choice_submit.html
{% extends "base.html" %}
{% load thumbnail staticfiles bleach_tags %}


{% block content %}
<a href="{% url 'topics:topic_view' topic.slug %}">&lt; Back</a>

<h1>{{ topic.title }}</h1>
<p class="lead">{{ topic.description|bleach|safe }}</p>
{% if topic.submission_information %}
<p class="lead">{{ topic.submission_information|bleach|safe }}</p>
{% endif %}

<form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form }}
<input type="submit" name="submit" value="submit">
</form>

{% endblock %}

vote_tool/templates/vote_tool/vote_choice_submit_success.html
{% extends "base.html" %}
{% load thumbnail staticfiles bleach_tags %}


{% block content %}
<a href="{% url 'topics:topic_view' topic.slug %}">&lt; Back</a>

<h1>{{ topic.title }}</h1>
<p>Thank you for your submission!</p>

{% if topic.require_approval %}
<p>Before this is listed as a votable choice, this will topic will
    approved by ChiPy.
</p>
{% endif %}

<p class="lead">{{ topic.description|bleach|safe }}</p>



{% endblock %}